@startuml

box "External World" #f6f6f6
    actor Player
    boundary Browser
end box

box "Inbound Adapter" #c0d0e0
    boundary GameController
end box

box "Application" #F3B467
    participant "GameService \n <<Service>>" as service
end box

box "Domain" #EDDE00
    entity "Game\n<<Aggregate Root>>" as Game
    entity "Scoreboard\n<<Entity>>" as Scoreboard
end box

Player -> Browser: Clicks [New Game]
Browser -> GameController: POST /start-game
GameController -> Game: start()
Game -> Scoreboard: new
Game <-- Scoreboard : scoreboard
GameController -> Browser: ScoreboardView
Player -> Browser: Click [Roll Dice]
Browser -> GameController: POST /rolldice
GameController -> Game: rollDice
Game -> Scoreboard: updateDiceRoll
GameController -> Browser: ScoreboardView
note left: 'Ask for Category'
Player -> Browser: Click [Some Category]
Browser -> GameController: POST /select-category
GameController -> Game: assign DiceRoll\nto Category

@enduml